In [1]:
import pandas as pd
import matplotlib.pyplot as plt
from pathlib import Path

In [2]:
path = Path.cwd() / 'datasets' / 'Loan_InitialDataset.csv'
df = pd.read_csv(path, sep = ';')
df = df.drop(columns=['User_ID2'])
df.head()

,Term,Interest_Pct,Loan_Grade,Loan_Sub_Grade,Emp_Tenure,House_Ownership,Is_Verified,Loan_Status,State,Fico,...,Delinquent_Accounts,User_ID,Loan_Applied,Loan_Committed,Disburse_Mode,Is_Hardship,Loan_Title,Is_Purpose_Credit_Card,Is_Ever_Bankrupt,Tax_Defaults
0,36 months,6.99,A,A3,9 years,MORTGAGE,Not Verified,0,TX,687.0,...,0,34871749,6000,6000,Online,0,Debt consolidation,0,0,0
1,36 months,12.05,C,C1,1 year,RENT,Source Verified,0,MI,662.0,...,0,31795137,2500,2500,Online,0,Debt consolidation,0,0,0
2,36 months,15.61,D,D1,8 years,RENT,Verified,0,CA,707.0,...,0,21182020,10000,10000,Online,0,Credit card refinancing,1,0,0
3,36 months,8.24,B,B1,3 years,OWN,Source Verified,0,FL,677.0,...,0,47553897,10000,10000,Online,0,Credit card refinancing,1,0,0
4,36 months,11.12,B,B3,4 years,MORTGAGE,Verified,0,NJ,717.0,...,0,265697,9875,9875,Online,0,Others,0,0,0

In [3]:
df.describe()

,Interest_Pct,Loan_Status,Fico,Rev_Util_Rate,High_Credit_Ratio,High_BC_Credit_Ratio,High_EMI_Credit_Ratio,DTI_Ratio,Total_Revolving_Ratio,Current_Bal_Avg,...,Accounts_90_dpd_Cur,Last6m_Inquiries,Delinquent_Accounts,User_ID,Loan_Applied,Loan_Committed,Is_Hardship,Is_Purpose_Credit_Card,Is_Ever_Bankrupt,Tax_Defaults
count,200.000000,200.000000,200.000000,200.000000,187.000000,189.000000,187.000000,200.000000,187.000000,187.000000,...,187.000000,200.000000,200.000000,2.000000e+02,200.000000,200.000000,200.0,200.00000,200.000000,200.000000
mean,13.430500,0.170000,695.925000,57.941950,188728.029412,25175.269312,42402.082353,10.581240,40936.081283,14991.022460,...,0.117647,0.805000,0.005000,2.657467e+07,7052.830000,7039.265000,0.0,0.21000,0.145000,0.015000
std,4.862238,0.376575,29.398824,26.899438,179829.192874,27180.755405,45036.194562,5.061273,40327.261787,15662.075447,...,0.483111,1.218358,0.070711,1.941580e+07,3858.001403,3845.267935,0.0,0.40833,0.352984,0.121857
min,5.320000,0.000000,662.000000,0.000000,7040.000000,0.000000,0.000000,0.258000,3480.000000,440.400000,...,0.000000,0.000000,0.000000,1.821270e+05,1000.000000,1000.000000,0.0,0.00000,0.000000,0.000000
25%,10.485000,0.000000,672.000000,37.097500,49616.600000,8580.000000,16059.450000,6.669000,15660.000000,3575.400000,...,0.000000,0.000000,0.000000,7.414615e+06,3978.000000,3978.000000,0.0,0.00000,0.000000,0.000000
50%,12.990000,0.000000,692.000000,58.520000,132720.500000,17490.000000,33055.000000,9.930000,29160.000000,9354.000000,...,0.000000,0.000000,0.000000,2.677492e+07,6000.000000,6000.000000,0.0,0.00000,0.000000,0.000000
75%,15.777500,0.000000,707.000000,78.897500,284660.200000,31460.000000,50383.300000,14.176500,48960.000000,22700.400000,...,0.000000,1.000000,0.000000,3.864462e+07,10000.000000,10000.000000,0.0,0.00000,0.000000,0.000000
max,30.940000,1.000000,822.000000,109.450000,968963.600000,221870.000000,321620.200000,26.874000,260400.000000,85344.000000,...,3.000000,4.000000,1.000000,7.281819e+07,17500.000000,17500.000000,0.0,1.00000,1.000000,1.000000

In [6]:
df.dtypes

Term                            object
Interest_Pct                   float64
Loan_Grade                      object
Loan_Sub_Grade                  object
Emp_Tenure                      object
House_Ownership                 object
Is_Verified                     object
Loan_Status                      int64
State                           object
Fico                           float64
Rev_Util_Rate                  float64
High_Credit_Ratio              float64
High_BC_Credit_Ratio           float64
High_EMI_Credit_Ratio          float64
DTI_Ratio                      float64
Total_Revolving_Ratio          float64
Current_Bal_Avg                float64
Bank_Card_Utilization_Ratio    float64
Collection_Fee                 float64
Never_Delinq_Act_Pct           float64
EMI                            float64
Payment_Recieved               float64
Principal_Recieved             float64
Late_Fee_Recieved              float64
Gross_Recovery                 float64
Last_Month_Pmnt                float64
All_Collection_Amount          float64
Cr_Balance                     float64
IPA                              int64
Delinquencies_2yr                int64
Open_Cr_Lines                    int64
Public_Derog_Rec                 int64
Revolving_Balance                int64
Tot_Cr_Lines                     int64
All_Current_Balance            float64
Last_24m_Accounts              float64
Amount_Owed_Delinq               int64
Months_Recent_Rev_Opened       float64
Accounts_Having_Mortgage       float64
Satisfactory_BC_Accounts       float64
Open_Rev_Accounts              float64
Satisfactory_Accounts          float64
Accounts_120_dpd_Ever          float64
Accounts_120_dpd_Cur           float64
Accounts_90_dpd_Cur            float64
Last6m_Inquiries                 int64
Delinquent_Accounts              int64
User_ID                          int64
Loan_Applied                     int64
Loan_Committed                   int64
Disburse_Mode                   object
Is_Hardship                      int64
Loan_Title                      object
Is_Purpose_Credit_Card           int64
Is_Ever_Bankrupt                 int64
Tax_Defaults                     int64
dtype: object

In [5]:
df_string = df.select_dtypes(include=['object'])
print(df_string)
# string_nan = df_string.columns[df.isna().any()].tolist()
# print(string_nan)

# for col in df.columns:
#     df[col].fillna(df[col].mode()[0], inplace=True)

           Term Loan_Grade Loan_Sub_Grade Emp_Tenure House_Ownership  \
0     36 months          A             A3    9 years        MORTGAGE
1     36 months          C             C1     1 year            RENT
2     36 months          D             D1    8 years            RENT
3     36 months          B             B1    3 years             OWN
4     36 months          B             B3    4 years        MORTGAGE
..          ...        ...            ...        ...             ...
195   36 months          E             E2  10+ years            RENT
196   36 months          B             B4   < 1 year            RENT
197   36 months          B             B2  10+ years            RENT
198   60 months          B             B4    3 years            RENT
199   60 months          D             D3  10+ years        MORTGAGE

         Is_Verified State Disburse_Mode               Loan_Title
0       Not Verified    TX        Online       Debt consolidation
1    Source Verified    MI        Online       Debt consolidation
2           Verified    CA        Online  Credit card refinancing
3    Source Verified    FL        Online  Credit card refinancing
4           Verified    NJ        Online                   Others
..               ...   ...           ...                      ...
195     Not Verified    NC        Online       Debt consolidation
196         Verified    NH        Online                   Others
197     Not Verified    CA        Online       Debt consolidation
198  Source Verified    PA        Online       Debt consolidation
199  Source Verified    CA        Online       Debt consolidation

[200 rows x 9 columns]

In [ ]:
nan_check = df.columns[df.isna().any()].tolist()
print(nan_check)